# vim:sw=2:et:
language: erlang
dist: bionic
sudo: false
otp_release:
  - "23.1.2"
  - "22.3.4"

install:
  - curl -O -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

script:
  - ./rebar3 do compile,eunit,dialyzer

after_success:
  - ./rebar3 coveralls send

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.cache/rebar3/hex/default
    - $HOME/_build/default/rebar3_${TRAVIS_OTP_RELEASE}_plt
