build: off

# Erlang 22.3 is only available in this image
image: "Visual Studio 2019"

install:
  - curl -OL https://s3.amazonaws.com/rebar3/rebar3

test_script:
  - escript ./rebar3 do compile,eunit,dialyzer

deploy: false
