name: CI

on:
    push:
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:21.3
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests, dialyzer
      run: rebar3 do eunit,dialyzer
